name: Release

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  packages: write

jobs:
  release:
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable pnpm
        run: corepack enable pnpm

      - name: Cache Dependency
        uses: actions/cache@v4
        id: cache_dependency_id
        env:
          cache-name: cache-dependency
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('.node-version') }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-node-${{ env.cache-name }}
      
      - if: ${{ steps.cache_dependency_id.outputs.cache-hit != 'true' }}
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Extract version
        id: extract-version
        run: |
          echo "version=$(node -p -e "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git tag v${{ steps.extract-version.outputs.version }}
          git push origin --tags

      - if: ${{ !contains(steps.extract-version.outputs.version, '-') }}
        name: Publish package
        run: pnpm publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - if: ${{ contains(steps.extract-version.outputs.version, '-') }}
        name: Publish canary package
        run: pnpm publish --tag next
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
